// preview.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, Input, OnChanges, SimpleChanges } from '@angular/core';
import sdk from '@stackblitz/sdk';

@Component({
  selector: 'app-live-preview',
  template: `<div #previewContainer style="height:100vh"></div>`,
  standalone: true
})
export class LivePreviewComponent implements AfterViewInit, OnChanges {
  @ViewChild('previewContainer', { static: true }) container!: ElementRef;
  @Input() generatedFiles: Record<string, string> | null = null;

  private hasInitialized = false;

  async ngAfterViewInit() {
    this.hasInitialized = true;
    this.initializePreview();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['generatedFiles'] && this.hasInitialized && !changes['generatedFiles'].firstChange) {
      this.initializePreview();
    }
  }

  private extractDependencies(packageJson: string | undefined): Record<string, string> {
    if (!packageJson) return {};
    try {
      const pkg = JSON.parse(packageJson);
      return { ...pkg.dependencies, ...pkg.devDependencies };
    } catch {
      return {};
    }
  }

  private async initializePreview() {
    if (!this.generatedFiles) return;

    const files = { ...this.generatedFiles };

    if (!files['src/main.ts']) {
      files['src/main.ts'] = `import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent)
  .catch(err => console.error(err));`;
    } else if (!files['src/main.ts'].includes("import 'zone.js'") && !files['src/main.ts'].includes('import "zone.js"')) {
      files['src/main.ts'] = `import 'zone.js';\n` + files['src/main.ts'];
    }

    if (files['src/index.html'] && !files['src/index.html'].includes('Material+Icons')) {
      files['src/index.html'] = files['src/index.html'].replace(
        '</head>',
        '  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">\n</head>'
      );
    }

    const dependencies = this.extractDependencies(files['package.json']);

    await sdk.embedProject(this.container.nativeElement, {
      title: 'Angular Live Preview',
      description: 'Generated by ProtoPilot LLM',
      template: 'angular-cli',
      files,
      dependencies,
    }, {
      openFile: 'src/app/app.component.ts',
      view: 'preview',
      height: 800
    });
  }
}
