// preview.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import sdk from '@stackblitz/sdk';

@Component({
  selector: 'app-live-preview',
  template: `<div #previewContainer style="height:100vh"></div>`
})
export class LivePreviewComponent implements AfterViewInit {
  @ViewChild('previewContainer', { static: true }) container!: ElementRef;

  async ngAfterViewInit() {
    const files = this.getMockProjectFiles();

    await sdk.embedProject(this.container.nativeElement, {
      title: 'Angular Live Preview',
      description: 'Generated by LLM',
      template: 'angular-cli',
      files,
      dependencies: {
        "@angular/core": "^17.0.0",
        "@angular/common": "^17.0.0",
        "@angular/platform-browser": "^17.0.0",
        "rxjs": "^7.8.0",
        "zone.js": "^0.14.0" // 👈 required
      }
    }, {
      openFile: 'src/app/app.component.ts',
      view: 'preview',
      height: 800
    });
  }

  getMockProjectFiles() {
    return {
      'src/main.ts': `
import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent)
  .catch(err => console.error(err));
`,

      'src/app/app.component.ts': `
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TodoService } from './todo.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html'
})
export class AppComponent {
  private todoService = inject(TodoService);

  newTodo = signal('');
  todos = this.todoService.todos;

  addTodo() {
    if (!this.newTodo().trim()) return;
    this.todoService.add(this.newTodo());
    this.newTodo.set('');
  }

  removeTodo(index: number) {
    this.todoService.remove(index);
  }
}

`,

      'src/app/app.component.html': `
<h1>📝 Todo App</h1>

<input
  [value]="newTodo()"
  (input)="newTodo.set($any($event.target).value)"
  placeholder="Add a task..."
/>
<button (click)="addTodo()">Add</button>

<ul>
  @for (todo of todos(); track $index) {
    <li>
      {{ todo }}
      <button (click)="removeTodo($index)">❌</button>
    </li>
  }
</ul>
`,

      'src/app/todo.service.ts': `
import { Injectable, signal } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TodoService {
  private _todos = signal<string[]>([]);
  // ✅ Expose as readonly — component binds to this directly
  todos = this._todos.asReadonly();

  add(todo: string) {
    this._todos.update(list => [...list, todo]);
  }

  remove(index: number) {
    this._todos.update(list => list.filter((_, i) => i !== index));
  }
}
`,

      'index.html': `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Angular Todo</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
`,

      'angular.json': `{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "projects": {
    "app": {
      "projectType": "application",
      "root": "",
      "sourceRoot": "src",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server"
        }
      }
    }
  }
}`
    };
  }
}