// preview.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, Input, OnChanges, SimpleChanges } from '@angular/core';
import sdk from '@stackblitz/sdk';

@Component({
  selector: 'app-live-preview',
  template: `<div #previewContainer style="height:100vh"></div>`,
  standalone: true
})
export class LivePreviewComponent implements AfterViewInit, OnChanges {
  @ViewChild('previewContainer', { static: true }) container!: ElementRef;
  @Input() generatedFiles: Record<string, string> | null = null;

  private hasInitialized = false;

  async ngAfterViewInit() {
    this.hasInitialized = true;
    this.initializePreview();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['generatedFiles'] && this.hasInitialized && !changes['generatedFiles'].firstChange) {
      this.initializePreview();
    }
  }

  private async initializePreview() {
    // let files = this.getMockProjectFiles();
    let files = this.getMockProjectFiles2();

    // Ensure main.ts exists
    if (!files['src/main.ts']) {
      files['src/main.ts'] = `import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent)
  .catch(err => console.error(err));`;
    }

    await sdk.embedProject(this.container.nativeElement, {
      title: 'Angular Live Preview',
      description: 'Generated by ProtoPilot LLM',
      template: 'angular-cli',
      files,
      // dependencies: {
      //   "@angular/core": "^17.0.0",
      //   "@angular/common": "^17.0.0",
      //   "@angular/platform-browser": "^17.0.0",
      //   "rxjs": "^7.8.0",
      //   "zone.js": "^0.14.0"
      // }
    }, {
      openFile: 'src/app/app.component.ts',
      view: 'preview',
      height: 800
    });
  }

  getMockProjectFiles() {
    return {
      'src/main.ts': `
import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent)
  .catch(err => console.error(err));
`,

      'src/app/app.component.ts': `
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TodoService } from './todo.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html'
})
export class AppComponent {
  private todoService = inject(TodoService);

  newTodo = signal('');
  todos = this.todoService.todos;

  addTodo() {
    if (!this.newTodo().trim()) return;
    this.todoService.add(this.newTodo());
    this.newTodo.set('');
  }

  removeTodo(index: number) {
    this.todoService.remove(index);
  }
}

`,

      'src/app/app.component.html': `
<h1>📝 Todo App</h1>

<input
  [value]="newTodo()"
  (input)="newTodo.set($any($event.target).value)"
  placeholder="Add a task..."
/>
<button (click)="addTodo()">Add</button>

<ul>
  @for (todo of todos(); track $index) {
    <li>
      {{ todo }}
      <button (click)="removeTodo($index)">❌</button>
    </li>
  }
</ul>
`,

      'src/app/todo.service.ts': `
import { Injectable, signal } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TodoService {
  private _todos = signal<string[]>([]);
  // ✅ Expose as readonly — component binds to this directly
  todos = this._todos.asReadonly();

  add(todo: string) {
    this._todos.update(list => [...list, todo]);
  }

  remove(index: number) {
    this._todos.update(list => list.filter((_, i) => i !== index));
  }
}
`,

      'index.html': `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Angular Todo</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
`,

      'angular.json': `{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "projects": {
    "app": {
      "projectType": "application",
      "root": "",
      "sourceRoot": "src",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server"
        }
      }
    }
  }
}`
    }
    
  }

  getMockProjectFiles2() {
    return {
      "src/app/features/task-manager/components/add-task-form/add-task-form.component.html": "\n<form [formGroup]=\"taskForm\" (ngSubmit)=\"onSubmit()\" class=\"add-task-form\">\n  <input formControlName=\"title\" placeholder=\"Add a new task...\" aria-label=\"New task title\" />\n  <button type=\"submit\" [disabled]=\"taskForm.invalid\">Add</button>\n</form>\n",
      "src/app/features/task-manager/components/add-task-form/add-task-form.component.scss": "\n.add-task-form {\n  display: flex;\n  gap: 8px;\n  margin-bottom: 24px;\n\n  input {\n    flex-grow: 1;\n    padding: 12px;\n    border: 1px solid #ccc;\n    border-radius: 4px;\n    font-size: 16px;\n\n    &:focus {\n      outline: none;\n      border-color: #007bff;\n      box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);\n    }\n  }\n\n  button {\n    padding: 12px 20px;\n    font-size: 16px;\n    color: #fff;\n    background-color: #007bff;\n    border: none;\n    border-radius: 4px;\n    cursor: pointer;\n    transition: background-color 0.2s;\n\n    &:hover {\n      background-color: #0056b3;\n    }\n\n    &:disabled {\n      background-color: #a0c7e4;\n      cursor: not-allowed;\n    }\n  }\n}\n",
      "src/app/features/task-manager/task-manager.component.ts": "\nimport { Component, OnInit, inject } from '@angular/core';\nimport { CommonModule } from '@angular/common';\nimport { Observable, BehaviorSubject, switchMap, catchError, of, tap } from 'rxjs';\nimport { Task } from '../../core/models/task.model';\nimport { TaskService } from '../../core/services/task.service';\nimport { AddTaskFormComponent } from './components/add-task-form/add-task-form.component';\nimport { TaskListComponent } from './components/task-list/task-list.component';\n\n@Component({\n  selector: 'app-task-manager',\n  standalone: true,\n  imports: [CommonModule, AddTaskFormComponent, TaskListComponent],\n  templateUrl: './task-manager.component.html',\n  styleUrls: ['./task-manager.component.scss']\n})\nexport class TaskManagerComponent implements OnInit {\n  private taskService = inject(TaskService);\n\n  tasks$!: Observable<Task[]>;\n  error: string | null = null;\n  loading = true;\n\n  private refreshTasks$ = new BehaviorSubject<void>(undefined);\n\n  ngOnInit() {\n    this.tasks$ = this.refreshTasks$.pipe(\n      tap(() => {\n        this.loading = true;\n        this.error = null;\n      }),\n      switchMap(() => this.taskService.getTasks()),\n      tap(() => this.loading = false),\n      catchError(err => {\n        this.error = 'Failed to load tasks.';\n        this.loading = false;\n        console.error(err);\n        return of([]);\n      })\n    );\n  }\n\n  handleAddTask(title: string) {\n    this.taskService.addTask(title).pipe(\n      catchError(err => {\n        this.error = 'Failed to add task.';\n        console.error(err);\n        return of(null);\n      })\n    ).subscribe(task => {\n      if (task) {\n        this.refreshTasks$.next();\n      }\n    });\n  }\n\n  handleCompleteTask(taskId: number) {\n    this.taskService.deleteTask(taskId).pipe(\n      catchError(err => {\n        this.error = 'Failed to complete task.';\n        console.error(err);\n        return of(null);\n      })\n    ).subscribe(result => {\n      // On successful deletion from service (which updates the signal), refresh the view\n      if (result === undefined) {\n         this.refreshTasks$.next();\n      }\n    });\n  }\n}\n",
      "src/app/core/services/task.service.ts": "\nimport { Injectable, signal } from '@angular/core';\nimport { of, Observable, throwError, delay } from 'rxjs';\nimport { Task } from '../models/task.model';\n\n@Injectable({\n  providedIn: 'root'\n})\nexport class TaskService {\n  private tasks = signal<Task[]>([]);\n  private initialTasks: Task[] = [\n    {\n      taskId: 1,\n      title: 'Finish the project report',\n      status: 'pending',\n      createdAt: '2023-10-27T10:00:00Z',\n      updatedAt: '2023-10-27T10:00:00Z'\n    },\n    {\n      taskId: 2,\n      title: 'Buy groceries',\n      status: 'pending',\n      createdAt: '2023-10-27T10:05:00Z',\n      updatedAt: '2023-10-27T10:05:00Z'\n    },\n    {\n      taskId: 3,\n      title: 'Schedule a dentist appointment',\n      status: 'pending',\n      createdAt: '2023-10-28T11:00:00Z',\n      updatedAt: '2023-10-28T11:00:00Z'\n    }\n  ];\n\n  constructor() {\n    this.tasks.set(this.initialTasks);\n  }\n\n  getTasks(): Observable<Task[]> {\n    // Mocking an API call with a delay\n    return of(this.tasks()).pipe(delay(500));\n  }\n\n  addTask(title: string): Observable<Task> {\n    if (!title.trim()) {\n      return throwError(() => new Error('Task title cannot be empty.'));\n    }\n\n    const newTask: Task = {\n      taskId: Math.floor(Math.random() * 1000) + 1, // Mocking ID generation\n      title: title,\n      status: 'pending',\n      createdAt: new Date().toISOString(),\n      updatedAt: new Date().toISOString()\n    };\n\n    this.tasks.update(tasks => [...tasks, newTask]);\n\n    // Mocking an API call with a delay\n    return of(newTask).pipe(delay(300));\n  }\n\n  deleteTask(taskId: number): Observable<void> {\n    const taskExists = this.tasks().some(task => task.taskId === taskId);\n    if (!taskExists) {\n      return throwError(() => new Error(`Task with id ${taskId} not found.`));\n    }\n\n    this.tasks.update(tasks => tasks.filter(task => task.taskId !== taskId));\n\n    // Mocking an API call with a delay\n    return of(undefined).pipe(delay(300));\n  }\n}\n",
      "src/app/features/task-manager/components/task-item/task-item.component.scss": "\n.task-item {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 16px;\n  background-color: #fff;\n  border: 1px solid #e0e0e0;\n  border-radius: 4px;\n  transition: box-shadow 0.2s;\n\n  &:not(:last-child) {\n    margin-bottom: 12px;\n  }\n\n  &:hover {\n    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n  }\n}\n\n.task-title {\n  font-size: 16px;\n  color: #333;\n}\n\n.complete-btn {\n  padding: 8px 16px;\n  font-size: 14px;\n  color: #fff;\n  background-color: #28a745;\n  border: none;\n  border-radius: 4px;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background-color: #218838;\n  }\n}\n",
      "src/app/core/models/task.model.ts": "\nexport interface Task {\n  taskId: number;\n  title: string;\n  status: 'pending' | 'completed';\n  createdAt: string;\n  updatedAt: string;\n}\n",
      "src/app/features/task-manager/components/task-item/task-item.component.ts": "\nimport { Component, Input, Output, EventEmitter } from '@angular/core';\nimport { CommonModule } from '@angular/common';\nimport { Task } from '../../../../core/models/task.model';\n\n@Component({\n  selector: 'app-task-item',\n  standalone: true,\n  imports: [CommonModule],\n  templateUrl: './task-item.component.html',\n  styleUrls: ['./task-item.component.scss']\n})\nexport class TaskItemComponent {\n  @Input({ required: true }) task!: Task;\n  @Output() complete = new EventEmitter<number>();\n\n  onComplete() {\n    this.complete.emit(this.task.taskId);\n  }\n}\n",
      "src/app/features/task-manager/components/task-list/task-list.component.html": "\n<div class=\"task-list-container\">\n  <div *ngIf=\"!tasks || tasks.length === 0; else taskItems\" class=\"empty-state\">\n    <p>No tasks yet. Add one above!</p>\n  </div>\n\n  <ng-template #taskItems>\n    <app-task-item\n      *ngFor=\"let task of tasks;\"\n      [task]=\"task\"\n      (complete)=\"onCompleteTask($event)\">\n    </app-task-item>\n  </ng-template>\n</div>\n",
      "src/app/features/task-manager/components/add-task-form/add-task-form.component.ts": "\nimport { Component, EventEmitter, Output, inject } from '@angular/core';\nimport { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';\nimport { CommonModule } from '@angular/common';\n\n@Component({\n  selector: 'app-add-task-form',\n  standalone: true,\n  imports: [CommonModule, ReactiveFormsModule],\n  templateUrl: './add-task-form.component.html',\n  styleUrls: ['./add-task-form.component.scss']\n})\nexport class AddTaskFormComponent {\n  @Output() addTask = new EventEmitter<string>();\n  private fb = inject(FormBuilder);\n\n  taskForm = this.fb.group({\n    title: ['', Validators.required]\n  });\n\n  onSubmit() {\n    if (this.taskForm.valid && this.taskForm.value.title) {\n      this.addTask.emit(this.taskForm.value.title);\n      this.taskForm.reset();\n    }\n  }\n}\n",
      "src/app/app.component.ts": "\nimport { Component } from '@angular/core';\nimport { CommonModule } from '@angular/common';\nimport { TaskManagerComponent } from './features/task-manager/task-manager.component';\n\n@Component({\n  selector: 'app-root',\n  standalone: true,\n  imports: [CommonModule, TaskManagerComponent],\n  template: '<app-task-manager></app-task-manager>',\n  styles: []\n})\nexport class AppComponent {\n  title = 'todo-frontend';\n}\n",
      "src/app/features/task-manager/components/task-list/task-list.component.scss": "\n.task-list-container {\n  background-color: #f9f9f9;\n  padding: 24px;\n  border-radius: 8px;\n}\n\n.empty-state {\n  text-align: center;\n  padding: 40px;\n  color: #888;\n  font-style: italic;\n}\n",
      "src/app/features/task-manager/task-manager.component.html": "\n<div class=\"task-manager\">\n  <header>\n    <h1>My Tasks</h1>\n  </header>\n\n  <app-add-task-form (addTask)=\"handleAddTask($event)\"></app-add-task-form>\n\n  <div *ngIf=\"loading\" class=\"loading-indicator\">Loading tasks...</div>\n\n  <div *ngIf=\"error\" class=\"error-message\">{{ error }}</div>\n\n  <div *ngIf=\"!loading && !error\">\n    <app-task-list [tasks]=\"tasks$ | async\" (completeTask)=\"handleCompleteTask($event)\"></app-task-list>\n  </div>\n</div>\n",
      "src/app/app.config.ts": "\nimport { ApplicationConfig, importProvidersFrom } from '@angular/core';\nimport { provideHttpClient } from '@angular/common/http';\n\nexport const appConfig: ApplicationConfig = {\n  providers: [provideHttpClient()]\n};\n",
      "src/app/features/task-manager/components/task-list/task-list.component.ts": "\nimport { Component, Input, Output, EventEmitter } from '@angular/core';\nimport { CommonModule } from '@angular/common';\nimport { Task } from '../../../../core/models/task.model';\nimport { TaskItemComponent } from '../task-item/task-item.component';\n\n@Component({\n  selector: 'app-task-list',\n  standalone: true,\n  imports: [CommonModule, TaskItemComponent],\n  templateUrl: './task-list.component.html',\n  styleUrls: ['./task-list.component.scss']\n})\nexport class TaskListComponent {\n  @Input() tasks: Task[] | null = [];\n  @Output() completeTask = new EventEmitter<number>();\n\n  onCompleteTask(taskId: number) {\n    this.completeTask.emit(taskId);\n  }\n}\n",
      "src/app/features/task-manager/components/task-item/task-item.component.html": "\n<div class=\"task-item\">\n  <span class=\"task-title\">{{ task.title }}</span>\n  <button (click)=\"onComplete()\" class=\"complete-btn\">Complete</button>\n</div>\n",
      "angular.json": "\n{\n  \"$schema\": \"./node_modules/@angular/cli/lib/config/schema.json\",\n  \"version\": 1,\n  \"newProjectRoot\": \"projects\",\n  \"projects\": {\n    \"todo-frontend\": {\n      \"projectType\": \"application\",\n      \"schematics\": {\n        \"@schematics/angular:component\": {\n          \"style\": \"scss\",\n          \"standalone\": true\n        },\n        \"@schematics/angular:directive\": {\n          \"standalone\": true\n        },\n        \"@schematics/angular:pipe\": {\n          \"standalone\": true\n        }\n      },\n      \"root\": \"\",\n      \"sourceRoot\": \"src\",\n      \"prefix\": \"app\",\n      \"architect\": {\n        \"build\": {\n          \"builder\": \"@angular-devkit/build-angular:browser\",\n          \"options\": {\n            \"outputPath\": \"dist/todo-frontend\",\n            \"index\": \"index.html\",\n            \"main\": \"src/main.ts\",\n            \"polyfills\": [\n              \"zone.js\"\n            ],\n            \"tsConfig\": \"tsconfig.app.json\",\n            \"inlineStyleLanguage\": \"scss\",\n            \"assets\": [\n              \"src/favicon.ico\",\n              \"src/assets\"\n            ],\n            \"styles\": [\n              \"src/styles.scss\"\n            ],\n            \"scripts\": []\n          },\n          \"configurations\": {\n            \"production\": {\n              \"budgets\": [\n                {\n                  \"type\": \"initial\",\n                  \"maximumWarning\": \"500kb\",\n                  \"maximumError\": \"1mb\"\n                },\n                {\n                  \"type\": \"anyComponentStyle\",\n                  \"maximumWarning\": \"2kb\",\n                  \"maximumError\": \"4kb\"\n                }\n              ],\n              \"outputHashing\": \"all\"\n            },\n            \"development\": {\n              \"buildOptimizer\": false,\n              \"optimization\": false,\n              \"vendorChunk\": true,\n              \"extractLicenses\": false,\n              \"sourceMap\": true,\n              \"namedChunks\": true\n            }\n          },\n          \"defaultConfiguration\": \"production\"\n        },\n        \"serve\": {\n          \"builder\": \"@angular-devkit/build-angular:dev-server\",\n          \"configurations\": {\n            \"production\": {\n              \"browserTarget\": \"todo-frontend:build:production\"\n            },\n            \"development\": {\n              \"browserTarget\": \"todo-frontend:build:development\"\n            }\n          },\n          \"defaultConfiguration\": \"development\"\n        },\n        \"extract-i18n\": {\n          \"builder\": \"@angular-devkit/build-angular:extract-i18n\",\n          \"options\": {\n            \"browserTarget\": \"todo-frontend:build\"\n          }\n        },\n        \"test\": {\n          \"builder\": \"@angular-devkit/build-angular:karma\",\n          \"options\": {\n            \"polyfills\": [\n              \"zone.js\",\n              \"zone.js/testing\"\n            ],\n            \"tsConfig\": \"tsconfig.spec.json\",\n            \"inlineStyleLanguage\": \"scss\",\n            \"assets\": [\n              \"src/favicon.ico\",\n              \"src/assets\"\n            ],\n            \"styles\": [\n              \"src/styles.scss\"\n            ],\n            \"scripts\": []\n          }\n        }\n      }\n    }\n  }\n}\n",
      "index.html": "    <!DOCTYPE html><html lang=\"en\">  <head>    <meta charset=\"utf-8\" />\n    <title>Angular Todo</title>\n    <base href=\"/\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n  </head>\n  <body>\n    <app-root></app-root>\n  </body>\n</html>",
      "package.json": "\n{\n  \"name\": \"todo-frontend\",\n  \"version\": \"0.0.0\",\n  \"scripts\": {\n    \"ng\": \"ng\",\n    \"start\": \"ng serve\",\n    \"build\": \"ng build\",\n    \"watch\": \"ng build --watch --configuration development\",\n    \"test\": \"ng test\"\n  },\n  \"private\": true,\n  \"dependencies\": {\n    \"@angular/animations\": \"^17.0.0\",\n    \"@angular/common\": \"^17.0.0\",\n    \"@angular/compiler\": \"^17.0.0\",\n    \"@angular/core\": \"^17.0.0\",\n    \"@angular/forms\": \"^17.0.0\",\n    \"@angular/platform-browser\": \"^17.0.0\",\n    \"@angular/platform-browser-dynamic\": \"^17.0.0\",\n    \"@angular/router\": \"^17.0.0\",\n    \"rxjs\": \"~7.8.0\",\n    \"tslib\": \"^2.3.0\",\n    \"zone.js\": \"~0.14.2\"\n  },\n  \"devDependencies\": {\n    \"@angular-devkit/build-angular\": \"^17.0.0\",\n    \"@angular/cli\": \"^17.0.0\",\n    \"@angular/compiler-cli\": \"^17.0.0\",\n    \"@types/jasmine\": \"~5.1.0\",\n    \"jasmine-core\": \"~5.1.0\",\n    \"karma\": \"~6.4.0\",\n    \"karma-chrome-launcher\": \"~3.2.0\",\n    \"karma-coverage\": \"~2.2.0\",\n    \"karma-jasmine\": \"~5.1.0\",\n    \"karma-jasmine-html-reporter\": \"~2.1.0\",\n    \"typescript\": \"~5.2.2\"\n  }\n}\n",
      "src/styles.scss": "\n/* You can add global styles to this file, and also import other style files */\nbody {\n  margin: 0;\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  background-color: #f4f5f7;\n  color: #333;\n}\n\n*, *::before, *::after {\n  box-sizing: border-box;\n}\n",
      "tsconfig.json": "\n{\n  \"compileOnSave\": false,\n  \"compilerOptions\": {\n    \"baseUrl\": \"./\",\n    \"outDir\": \"./dist/out-tsc\",\n    \"forceConsistentCasingInFileNames\": true,\n    \"strict\": true,\n    \"noImplicitOverride\": true,\n    \"noPropertyAccessFromIndexSignature\": true,\n    \"noImplicitReturns\": true,\n    \"noFallthroughCasesInSwitch\": true,\n    \"sourceMap\": true,\n    \"declaration\": false,\n    \"downlevelIteration\": true,\n    \"experimentalDecorators\": true,\n    \"moduleResolution\": \"node\",\n    \"importHelpers\": true,\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \"useDefineForClassFields\": false,\n    \"lib\": [\n      \"ES2022\",\n      \"dom\"\n    ]\n  },\n  \"angularCompilerOptions\": {\n    \"enableI18nLegacyMessageIdFormat\": false,\n    \"strictInjectionParameters\": true,\n    \"strictInputAccessModifiers\": true,\n    \"strictTemplates\": true\n  }\n}\n",
      "src/main.ts": "\nimport 'zone.js'; import { bootstrapApplication } from '@angular/platform-browser';\nimport { appConfig } from './app/app.config';\nimport { AppComponent } from './app/app.component';\n\nbootstrapApplication(AppComponent, appConfig)\n  .catch((err) => console.error(err));\n",
      "src/app/features/task-manager/task-manager.component.scss": "\n.task-manager {\n  max-width: 700px;\n  margin: 40px auto;\n  padding: 24px;\n  font-family: 'Helvetica Neue', Arial, sans-serif;\n}\n\nheader {\n  text-align: center;\n  margin-bottom: 24px;\n\n  h1 {\n    font-size: 36px;\n    color: #333;\n    font-weight: 300;\n  }\n}\n\n.loading-indicator {\n  text-align: center;\n  padding: 20px;\n  font-size: 18px;\n  color: #555;\n}\n\n.error-message {\n  text-align: center;\n  padding: 20px;\n  background-color: #f8d7da;\n  color: #721c24;\n  border: 1px solid #f5c6cb;\n  border-radius: 4px;\n  margin-bottom: 20px;\n}\n"


    }
  }
}